[package]
name = "wasm-best-path"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
best-path = { version = '0.1.1', default-features = false }

[dev-dependencies]
wasm-bindgen-test = "0.3"